---
- hosts: [loadgen]
  roles:
    - common
    - loadgen
  tasks:


    - name: Start read-modify-write workload 1
      vars:
        cmd: "/opt/aerospike/bin/asbenchmark -S {{ start_key }} -k {{ num_keys }} -o S:{{ str_val_len }} -R -w RU,50,0,0 -n test -h {{ as_private_ips | join(',') }} -latency 14,1 -z {{ rmw_thread_count }} -Y {{ connections_per_node}} |tee {{ home_dir }}/{{ log_file_rmw }}"
      shell: "{{ cmd }}"
      async: 100000000
      poll: 0
      register: out
    - debug: var=out.stdout_lines

