---
- hosts: [loadgen]
  roles:
    - common
    - loadgen
  tasks:
    - name: Kill all benchmarks
      become: true
      shell: "pkill -f aerospike-benchmarks"
      register: out1
      ignore_errors: true
    - debug: var=out1.stdout_lines

    - name: Start read-batch workload
      vars:
        cmd: "/opt/aerospike/bin/asbenchmark -S 1 -k {{ num_keys }} -o S:{{ str_val_len }} -R -w RU,100,0,0 -B {{readbatch_size}} -BT {{readbatch_thread_count}} -n test -h {{ as_private_ips | join(',') }} -latency 25,1 -Y {{ connections_per_node}} -T 10000 |tee {{ home_dir }}/{{ log_file_readbatch }}"
      shell: "{{ cmd }}"
      async: 100000000
      poll: 0
      register: out

    - debug: var=out.stdout_lines